site_name: Catalog

plugins:
  - search
  - include-markdown
#   - tags:
#       tags_file: tags.md
#  - blog

theme:
  name: material

nav:
#    - About: about.md
    - Data Harvesting: data-harvesting.md
    - Source Code:
      - Database: ../src/catalog/core/db.py
      - CLI: ../src/catalog/cli/cli.py
#   - Metadata Sources: metadata-sources.md
#   - Harvesting: data-harvesting.md
#   - Storage: data-storage.md
#   - API: api.md
#   - LLM: llm.md
#   - Client: client.md
