[project]
name = "catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

authors = [
    { name = "acatejr@gmail.com", email = "acatejr@gmail.com" }
]

requires-python = ">=3.13"

dependencies = [
    "bs4>=0.0.2",
    "chromadb>=1.3.6",
    "click>=8.3.1",
    "langchain>=1.1.2",
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.0.0",
    "lxml>=6.0.2",
    "mkdocs-material>=9.7.0",
    "mkdocs-mermaid2-plugin>=1.2.3",
    "openai>=2.9.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "sentence-transformers>=5.1.2",
    "sqlite-vec>=0.1.6",
    "tabulate>=0.9.0",
]

[project.scripts]
timbercat = "catalog:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-sugar>=1.1.1",
    "ruff>=0.14.6",
]
