[project]
name = "catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "click>=8.3.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]

[project.scripts]
catalog = "catalog.cli:main"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-sugar>=1.1.1",
    "ruff>=0.14.14",
]

[build-system]
 requires = ["uv_build>=0.9.22,<0.10.0"]
 build-backend = "uv_build"
