[project]
name = "catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "click>=8.3.1",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-sugar>=1.1.1",
    "ruff>=0.14.13",
]

[project.scripts]
timbercat = "catalog.cli:main"

[build-system]
requires = ["hatchling", "setuptools", "wheel"]

[tool.hatch.build.targets.wheel]
packages = ["src/catalog"]
